Tarea3IS/urls.py
from django.contrib import admin
from django.urls import path
from articulos import views
from userlanding import views as user_views
from adminlanding import views as admin_views
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.conf import settings
from userprofile import views as userprofileviews
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/busqueda/', user_views.busqueda, name='nombre_articulo'),
    path('user/espacios', user_views.espacios),
    path('administracion/reservas/', admin_views.reservas),
    path('administracion/grilla', admin_views.grilla),
    path('articulos/<int:id_articulo>/', views.id_articulo, name='id_articulo'),
    path('articulos/<int:id_articulo>/edit', views.editar, name='id_articulo'),
    path('exito/', views.exito),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('perfil/', userprofileviews.perfilUsuario, name = 'perfilUsuario'),
    path('register/', userprofileviews.signup, name = 'register'),
    path('home/', userprofileviews.index, name = 'home'),
    path('', userprofileviews.redirectToHome),
    path('change_password/', userprofileviews.change_password, name='change_password'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminlanding/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('/reservas/', views.reservas),
    path('/grilla/', views.grilla),
]

prestamos/models.py
from django.db import models
from userprofile.models import Perfil
from reservas.models import ReservaArticulo
from reservas.models import ReservaEspacio

class PrestamoArticulo(models.Model):
    reserva = models.ForeignKey(ReservaArticulo, on_delete=models.CASCADE)
    administrador = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    ESTADOS_PRES = ((1, 'Vigente'), (2, 'Caducado'), (3, 'Perdido'))
    estado_prestamo = models.IntegerField(choices=ESTADOS_PRES, default=1)

class PrestamoEspacio(models.Model):
    reserva = models.ForeignKey(ReservaEspacio, on_delete=models.CASCADE)
    administrador = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    ESTADOS_PRES = ((1, 'Vigente'), (2, 'Caducado'), (3, 'Perdido'))
    estado_prestamo = models.IntegerField(choices=ESTADOS_PRES, default=1)

adminlanding/views.py
from django.shortcuts import render, redirect
from datetime import date
from datetime import timedelta
from datetime import datetime
from espacios.models import Espacios
from userprofile.models import Perfil
from reservas.models import ReservaArticulo
from reservas.models import ReservaEspacio
from prestamos.models import PrestamoArticulo
from prestamos.models import PrestamoEspacio
from django.http import HttpResponseRedirect

def week_range(date):
    """Find the first/last day of the week for the given day.
    Assuming weeks start on Sunday and end on Saturday.

    Returns a tuple of ``(start_date, end_date)``.

    """
    # isocalendar calculates the year, week of the year, and day of the week.
    # dow is Mon = 1, Sat = 6, Sun = 7
    year, week, dow = date.isocalendar()

    # Find the first day of the week.
    if dow == 7:
        # Since we want to start with Sunday, let's test for that condition.
        start_date = date
    else:
        # Otherwise, subtract `dow` number days to get the first day
        start_date = date - timedelta(dow)

    # Now, add 6 for the last day of the week (i.e., count up to Saturday)
    end_date = start_date + timedelta(5)

    return (start_date, end_date)

def reservas(request):
    if not request.user.is_authenticated or not request.user.is_superuser:
        return redirect('/home/')
    else:
        perfil = Perfil.objects.get(correo=request.user.id)
        reservas_articulos = ReservaArticulo.objects.filter(estado_reserva=1)
        reservas_espacios = ReservaEspacio.objects.filter(estado_reserva=1)
        prestamos_articulos = PrestamoArticulo.objects.all()
        prestamos_espacios = PrestamoEspacio.objects.all()
        lista_reservas = list(reservas_articulos)+list(reservas_espacios)
        lista_prestamos = list(prestamos_articulos)+list(prestamos_espacios)
        lista_reservas.sort(key=lambda x: x.inicio)
        lista_prestamos.sort(key=lambda x: x.reserva.inicio)
        if request.method == 'POST':
            if 'todos' in request.POST:
                prestamos_articulos = PrestamoArticulo.objects.all()
                prestamos_espacios = PrestamoEspacio.objects.all()
                lista_prestamos = list(prestamos_articulos) + list(prestamos_espacios)
                context = {'perfil': perfil, 'lista_reservas': lista_reservas, 'lista_prestamos': lista_prestamos}
                return render(request, 'admin_landing/admin_reservas.html', context)
            elif 'filtro' in request.POST:
                prestamos_articulos = PrestamoArticulo.objects.filter(estado_prestamo=request.POST.get("filtro",""))
                prestamos_espacios = PrestamoEspacio.objects.filter(estado_prestamo=request.POST.get("filtro",""))
                lista_prestamos = list(prestamos_articulos) + list(prestamos_espacios)
                context = {'perfil': perfil, 'lista_reservas': lista_reservas, 'lista_prestamos': lista_prestamos}
                return render(request, 'admin_landing/admin_reservas.html', context)
            elif 'entregar' in request.POST:
                presionados = request.POST.getlist('checks[]')
                for marcado in presionados:
                    info = marcado.split(" ")
                    if 'ReservaArticulo' in info:
                        reserva = ReservaArticulo.objects.get(pk=info[0])
                        reserva.estado_reserva = 2
                        query = PrestamoArticulo(reserva=reserva, administrador=perfil, estado_prestamo=1)
                        query.save()
                        reserva.save()
                    else:
                        reserva = ReservaEspacio.objects.get(pk=info[0])
                        reserva.estado_reserva = 2
                        query = PrestamoEspacio(reserva=reserva, administrador=perfil, estado_prestamo=1)
                        query.save()
                        reserva.save()
                return HttpResponseRedirect('/administracion/reservas/')
            elif 'rechazar' in request.POST:
                presionados = request.POST.getlist('checks[]')
                for marcado in presionados:
                    info = marcado.split(" ")
                    if 'ReservaArticulo' in info:
                        reserva = ReservaArticulo.objects.get(pk=info[0])
                        reserva.estado_reserva = 3
                        reserva.save()
                    else:
                        reserva = ReservaEspacio.objects.get(pk=info[0])
                        reserva.estado_reserva = 3
                        reserva.save()
                    return HttpResponseRedirect('/administracion/reservas/')
        else:
            context = {'perfil': perfil, 'lista_reservas': lista_reservas, 'lista_prestamos': lista_prestamos}
            return render(request, 'admin_landing/admin_reservas.html', context)

def grilla(request):
    if not request.user.is_authenticated or not request.user.is_superuser:
        return redirect('/home/')

    todo_espacios = Espacios.objects.all()

    reservas = ReservaEspacio.objects.all()
    delta = request.GET.get("delta")
    if not delta:
        delta = 0

    delta = int(delta)
    today = date.today()
    today_day = today.strftime("%A")

    mon = week_range(today)[0] + timedelta(days=(1 + 7 * delta))
    tue = mon + timedelta(days=1)
    wed = tue + timedelta(days=1)
    thu = wed + timedelta(days=1)
    fri = thu + timedelta(days=1)

    semana = "Semana del lunes " + str(mon.day) + "/" + str(mon.month) + "/" + str(mon.year)

    seleccion = request.GET.get("espacio")
    if seleccion and seleccion != "0":
        espacio_seleccionado = todo_espacios.get(id=seleccion)
    else:
        espacio_seleccionado = todo_espacios.first()

    reservas = reservas.filter(espacio=espacio_seleccionado)

    reservas_mon = reservas.filter(inicio__day=mon.day).filter(inicio__month=mon.month).filter(inicio__year=mon.year)
    reservas_tue = reservas.filter(inicio__day=tue.day).filter(inicio__month=tue.month).filter(inicio__year=tue.year)
    reservas_wed = reservas.filter(inicio__day=wed.day).filter(inicio__month=wed.month).filter(inicio__year=wed.year)
    reservas_thu = reservas.filter(inicio__day=thu.day).filter(inicio__month=thu.month).filter(inicio__year=thu.year)
    reservas_fri = reservas.filter(inicio__day=fri.day).filter(inicio__month=fri.month).filter(inicio__year=fri.year)

    perfil = Perfil.objects.get(correo=request.user.id)

    context = {'espacios': todo_espacios, 'seleccionado': espacio_seleccionado, 'deltaPlus': delta + 1,
               'deltaSub': delta - 1, 'deltaPlus4': delta + 4, 'deltaSub4': delta - 4, 'semana': semana, 'lunes': reservas_mon, 'martes': reservas_tue,
               'miercoles': reservas_wed, 'jueves': reservas_thu, 'viernes': reservas_fri, 'perfil': perfil}

    return render(request, 'admin_landing/admin_grilla.html', context)

templates/admin_landing/admin_grilla.html
{% extends "Layouts/GeneralLayout.html" %}
{% load static %}
{% load bootstrap4 %}

{% block cabeza %}

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}"> <!-- CSS reset -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Resource style -->
    <meta charset="UTF-8">
    <title>Grilla de Horarios</title>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-1" style="margin-top: 250px">
                <button type="button" class="btn btn-primary">Usuarios</button>
                <br/>
                <br/>
                <button type="button" class="btn btn-secondary">Objetos</button>
                <br/>
                <br/>
                <button type="button" class="btn btn-success">Reservas</button>
            </div>
            <div class="col-11">
                <h1> Administrador </h1>
                <hr>
                <div class="container">

                    <div class="row" style="height:20px;"></div>

                    <div class="row">
                        <div class="column ml-auto">
                            <a type="button" href="/administracion/reservas" class="btn" role="button">Reservas y
                                Préstamos</a>
                        </div>
                        <div class="column mr-auto">
                            <a type="button" class="btn btn-success" role="button">Grilla Espacios</a>
                        </div>
                    </div>
                </div>


                <div class="container">


                    <div class="container">
                        <form method="GET">
                            <div class="row no-gutters">
                                <div class="col-7 ml-auto">
                                    <select name="espacio" class="form-control">
                                        <option value="0">Seleccione un espacio</option>
                                        {% for espacio in espacios %}
                                            {% if espacio.id == seleccionado.id %}
                                                <option selected="selected"
                                                        value="{{ espacio.id }}">{{ espacio.nombre_espacio }}</option>
                                            {% else %}
                                                <option value="{{ espacio.id }}">{{ espacio.nombre_espacio }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="col-3 mr-auto">
                                    <input type="submit" value="Actualizar" class="form-control">
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="row" style="height:20px;"></div>

                    <div class="col-12 ml-auto mr-auto">
                        <h1 align="center"> Horarios de {{ seleccionado.nombre_espacio }}</h1>

                    </div>

                    <div class="container-fuid">
                        <div class="row">
                            <div class="column mr-auto ml-auto">
                                {{ semana }}
                            </div>
                        </div>


                    </div>
                </div>


                <div class="cd-schedule loading">
                    <div class="timeline">
                        <ul>
                            <li><span>09:00</span></li>
                            <li><span>10:30</span></li>
                            <li><span>12:00</span></li>
                            <li><span>13:30</span></li>
                            <li><span>15:00</span></li>
                            <li><span>16:30</span></li>
                            <li><span>18:00</span></li>
                        </ul>
                    </div> <!-- .timeline -->

                    <div class="events">
                        <ul>
                            <li class="events-group">
                                <div class="top-info"><span>Lunes</span></div>

                                <ul>
                                    {% for reserva in lunes %}

                                        <li class="single-event" data-start="{{ reserva.inicio|time }}"
                                            data-end="{{ reserva.final|time }}" data-event="event-1">
                                            <a href="#0">
                                                <em class="event-name">Reservado</em>
                                            </a>
                                        </li>

                                    {% endfor %}

                                </ul>
                            </li>

                            <li class="events-group">
                                <div class="top-info"><span>Martes</span></div>

                                <ul>
                                    {% for reserva in martes %}

                                        <li class="single-event" data-start="{{ reserva.inicio|time }}"
                                            data-end="{{ reserva.final|time }}" data-event="event-1">
                                            <a href="#0">
                                                <em class="event-name">Reservado</em>
                                            </a>
                                        </li>

                                    {% endfor %}
                                </ul>
                            </li>

                            <li class="events-group">
                                <div class="top-info"><span>Miércoles</span></div>

                                <ul>
                                    {% for reserva in miercoles %}

                                        <li class="single-event" data-start="{{ reserva.inicio|time }}"
                                            data-end="{{ reserva.final|time }}" data-event="event-1">
                                            <a href="#0">
                                                <em class="event-name">Reservado</em>
                                            </a>
                                        </li>

                                    {% endfor %}
                                </ul>
                            </li>

                            <li class="events-group">
                                <div class="top-info"><span>Jueves</span></div>

                                <ul>
                                    {% for reserva in jueves %}

                                        <li class="single-event" data-start="{{ reserva.inicio|time }}"
                                            data-end="{{ reserva.final|time }}" data-event="event-1">
                                            <a href="#0">
                                                <em class="event-name">Reservado</em>
                                            </a>
                                        </li>

                                    {% endfor %}
                                </ul>
                            </li>

                            <li class="events-group">
                                <div class="top-info"><span>Viernes</span></div>

                                <ul>
                                    {% for reserva in viernes %}

                                        <li class="single-event" data-start="{{ reserva.inicio|time }}"
                                            data-end="{{ reserva.final|time }}" data-event="event-1">
                                            <a href="#0">
                                                <em class="event-name">Reservado</em>
                                            </a>
                                        </li>

                                    {% endfor %}
                                </ul>
                            </li>

                        </ul>
                    </div>

                    <div class="event-modal">
                        <header class="header">
                            <div class="content">
                                <span class="event-date"></span>
                                <h3 class="event-name"></h3>
                            </div>

                            <div class="header-bg"></div>
                        </header>

                        <div class="body">
                            <div class="event-info"></div>
                            <div class="body-bg"></div>
                        </div>

                        <a href="#0" class="close">Close</a>
                    </div>

                    <div class="cover-layer"></div>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-2 ml-auto">
                            <form method="GET">
                                <input style="display:none" type="text" name="espacio" value="{{ seleccionado.id }}">
                                <input style="display:none" type="text" name="delta" value="{{ deltaSub4 }}">
                                <input class="form-control" type="submit" value="<<<">
                            </form>
                        </div>

                        <div class="col-2 ml-auto">
                            <form method="GET">
                                <input style="display:none" type="text" name="espacio" value="{{ seleccionado.id }}">
                                <input style="display:none" type="text" name="delta" value="{{ deltaSub }}">
                                <input class="form-control" type="submit" value="<">
                            </form>
                        </div>

                        <div class="col-3">
                            <form method="GET">
                                <input style="display:none" type="text" name="espacio"
                                       value="{{ seleccionado.id }}">
                                <input style="display:none" type="text" name="delta" value="0">
                                <input class="form-control" type="submit" value="Semana actual">
                            </form>
                        </div>

                        <div class="col-2 mr-auto">
                            <form method="GET">
                                <input style="display:none" type="text" name="espacio" value="{{ seleccionado.id }}">
                                <input style="display:none" type="text" name="delta" value="{{ deltaPlus }}">
                                <input class="form-control" type="submit" value=">">
                            </form>
                        </div>

                        <div class="col-2 mr-auto">
                            <form method="GET">
                                <input style="display:none" type="text" name="espacio" value="{{ seleccionado.id }}">
                                <input style="display:none" type="text" name="delta" value="{{ deltaPlus4 }}">
                                <input class="form-control" type="submit" value=">>>">
                            </form>
                        </div>
                    </div>
                </div>


                <script src="{% static 'js/modernizr.js' %}"></script>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
                <script>
                    if (!window.jQuery) document.write('<script src="js/jquery-3.0.0.min.js"><\/script>');
                </script>
                <script src="{% static 'js/main.js' %}"></script> <!-- Resource jQuery -->

            </div>


        </div>
    </div>
    </div>
{% endblock %}

templates/admin_landing/admin_reservas.html
{% extends "Layouts/GeneralLayout.html" %}
{% load static %}
{% load bootstrap4 %}

{% block cabeza %}

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}"> <!-- CSS reset -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Resource style -->
    <style>
        .bodycontainer {max-height: 220px;width: 100%; margin: 0; overflow-y: auto; }
    </style>
    <meta charset="UTF-8">
    <title>Reservas y Prestamos</title>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-1" style="margin-top: 250px">
                <button type="button" class="btn btn-primary">Usuarios</button>
                <br/>
                <br/>
                <button type="button" class="btn btn-secondary">Objetos</button>
                <br/>
                <br/>
                <button type="button" class="btn btn-success">Reservas</button>
            </div>
            <div class="col-11">
                <h1> Administrador </h1>
                <hr>
                <div class="container">
                    <div class="row" style="height:20px;"></div>
                    <div class="row">
                        <div class="column ml-auto">
                            <a type="button" class="btn btn-success" role="button">Reservas y Préstamos</a>
                        </div>
                        <div class="column mr-auto">
                            <a type="button" href="/administracion/grilla" class="btn" role="button">Grilla Espacios</a>
                        </div>
                    </div>
                </div>
                <br/>
                <form action="" method="post">{% csrf_token %}
                    <h3> Pendientes <button type="submit" class="btn btn-danger float-right" name="rechazar">Rechazar</button>
                        <button type="submit" class="btn btn-success float-right" name="entregar">Entregar</button>
                    </h3>
                    <div class="bodycontainer scrollable">
                        <table class="table table-hover table-striped">
                            <thead>
                        <tr>
                            <th scope="col">Check</th>
                            <th scope="col">ID</th>
                            <th scope="col">Objeto</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Inicio</th>
                            <th scope="col">Fin</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for reserva in lista_reservas %}
                            <tr>
                                <td><div class="form-check">
                                    <input type="checkbox" value="{{ reserva.id }} {{ reserva.get_cname }}" name="checks[]">
                                </div></td>
                                <td>{{ reserva.id }}</td>
                                {% if reserva.get_cname == 'ReservaArticulo' %}
                                <td><a href="/articulos/{{ reserva.articulo.id }}">{{ reserva.articulo.nombre_articulo }}</a></td>
                                {% else %}
                                <td><a href="#">{{ reserva.espacio.nombre_espacio }}</a></td>
                                {% endif %}
                                <td>{{ reserva.perfil.nombre }}</td>
                                <td>{{ reserva.inicio }}</td>
                                <td>{{ reserva.final }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </form>
            <hr/>
            <form action="" method="post">{% csrf_token %}
                <h3> Préstamos
                    <button type="button" class="btn btn-danger float-right" name="perdido">Perdido</button>
                    <button type="button" class="btn btn-success float-right" name="recibido">Recibido</button>
                    <button type="submit" class="btn btn-primary float-right" name="filtro" value="3">Perdidos</button>
                    <button type="submit" class="btn btn-primary float-right" name="filtro" value="2">Caducados</button>
                    <button type="submit" class="btn btn-primary float-right" name="filtro" value="1">Vigentes</button>
                    <button type="submit" class="btn btn-primary float-right" name="todos">Todos</button>
                </h3>
                <div class="bodycontainer scrollable">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Check</th>
                            <th scope="col">ID</th>
                            <th scope="col">Objeto</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Inicio</th>
                            <th scope="col">Fin</th>
                            <th scope="col">Estado</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for prestamo in lista_prestamos %}
                            <tr>
                                <td><div class="form-check">
                                    <input type="checkbox">
                                </div></td>
                                <td>{{ prestamo.id }}</td>
                                {% if prestamo.reserva.get_cname == 'ReservaArticulo' %}
                                    <td><a href="/articulos/{{ prestamo.reserva.articulo.id }}">{{ prestamo.reserva.articulo.nombre_articulo }}</a></td>
                                {% else %}
                                    <td><a href="#">{{ prestamo.reserva.espacio.nombre_espacio }}</a></td>
                                {% endif %}
                                <td>{{ prestamo.reserva.perfil.nombre }}</td>
                                <td>{{ prestamo.reserva.inicio }}</td>
                                <td>{{ prestamo.reserva.final }}</td>
                                <td>{{ prestamo.get_estado_prestamo_display }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}