Tarea3IS/urls.py
from django.contrib import admin
from django.urls import path
from articulos import views
from userlanding import views as user_views
from adminlanding import views as admin_views
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.conf import settings
from userprofile import views as userprofileviews
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/busqueda/', user_views.busqueda, name='nombre_articulo'),
    path('user/espacios', user_views.espacios),
    path('administracion/reservas/', admin_views.reservas),
    path('administracion/grilla', admin_views.grilla),
    path('articulos/<int:id_articulo>/', views.id_articulo, name='id_articulo'),
    path('articulos/<int:id_articulo>/edit', views.editar, name='id_articulo'),
    path('exito/', views.exito),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('perfil/', userprofileviews.perfilUsuario, name = 'perfilUsuario'),
    path('register/', userprofileviews.signup, name = 'register'),
    path('home/', userprofileviews.index, name = 'home'),
    path('', userprofileviews.redirectToHome),
    path('change_password/', userprofileviews.change_password, name='change_password'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('/<int:id_articulo>/', views.id_articulo, name='id_articulo'),
    path('/<int:id_articulo>/edit', views.editar, name='editar'),
]

articulos/models.py
from django.db import models


class Articulos(models.Model):

    ESTADOS_ART = ((1, 'Disponible'), (2, 'Prestado'), (3, 'Reparación'), (4, 'Perdido'))
    estado_articulo = models.IntegerField(choices=ESTADOS_ART, default=1)
    nombre_articulo = models.CharField(max_length=200)
    descripcion_articulo = models.CharField(max_length=1500)
    foto_articulo = models.ImageField(upload_to='uploads/fotos_articulos')

    def __str__(self):
        return self.nombre_articulo

articulos/forms.py
from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms
from datetime import datetime,timedelta


class ReservaForm(forms.Form):
    inicio = forms.DateTimeField(
        label= 'Fecha Inicio',
        widget=DateTimePickerInput(
            options={
                    "format": "DD/MM/YYYY HH:mm", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": False,
                    "defaultDate": (datetime.now()+timedelta(hours=1)).strftime("%m/%d/%Y %H:%M"),
                    "minDate": (datetime.now()+timedelta(hours=1)).strftime("%m/%d/%Y %H:%M"),
                    "sideBySide": True,
                    "daysOfWeekDisabled": [0,6],
                    "stepping": 15,
                    "keepInvalid": True,
                })
    )
    fin = forms.DateTimeField(
        label= 'Fecha Fin',
        widget=DateTimePickerInput(
            options={
                "format": "DD/MM/YYYY HH:mm",  # moment date-time format
                "showClose": True,
                "showClear": True,
                "showTodayButton": False,
                "defaultDate": (datetime.now() + timedelta(hours=1, minutes=30)).strftime("%m/%d/%Y %H:%M"),
                "minDate": (datetime.now() + timedelta(hours=1, minutes=30)).strftime("%m/%d/%Y %H:%M"),
                "sideBySide": True,
                "daysOfWeekDisabled": [0, 6],
                "stepping": 15,
                "keepInvalid": True,
            }
        )
    )

    def clean(self):
        cleaned_data = super().clean()
        inicio = cleaned_data.get("inicio")
        fin = cleaned_data.get("fin")
        if inicio and fin:
            # Only do something if both fields are valid so far.
            if fin <= inicio:
                raise forms.ValidationError(
                    "La fecha final debe ser posterior a la inicial."
                )
            if inicio.hour < 9 or inicio.hour > 17:
                msg = "La hora de inicio debe estar entre las 9:00 y 18:00."
                self.add_error('inicio', msg)
            if fin.hour < 9 or (fin.hour == 18 and fin.minute > 0) or fin.hour > 18:
                msg = "La hora de fin debe estar entre las 9:00 y 18:00."
                self.add_error('fin', msg)
            if abs((inicio.day*24*60+inicio.hour*60+inicio.minute)-(datetime.now().day*60*24+datetime.now().hour*60+datetime.now().minute))<60:
                msg = "La hora de inicio debe ser en al menos una hora más."
                self.add_error('inicio', msg)

articulos/views.py
from django.shortcuts import render,redirect
from .models import Articulos
from userprofile.models import Perfil
from reservas.models import ReservaArticulo
from django.core.files.storage import FileSystemStorage
from datetime import datetime
from django.utils import timezone
from django.conf import settings
from .forms import ReservaForm
from django.http import HttpResponseRedirect


def id_articulo(request, id_articulo):
    if not request.user.is_authenticated:
        return redirect('/home/')
    else:
        perfil = Perfil.objects.get(correo=request.user.id)
        articulo = Articulos.objects.get(pk=id_articulo)
        reservas = ReservaArticulo.objects.filter(articulo=articulo, final__lt=timezone.make_aware(datetime.now(), timezone.get_current_timezone()))
        lista_reservas=list(reservas)
        lista_reservas.sort(key=lambda x: x.final, reverse=True)
        lista_reservas = lista_reservas[:10]
        if request.user.is_superuser:
            if request.method == 'POST':
                if 'guardar' in request.POST:
                    articulo.nombre_articulo = request.POST.get("new_name","")
                    articulo.descripcion_articulo = request.POST.get("new_descr","")
                    if len(request.FILES) != 0:
                        old_path = articulo.foto_articulo
                        myfile = request.FILES['new_foto']
                        fs = FileSystemStorage()
                        new_path = settings.MEDIA_ROOT + "/uploads/fotos_articulos/"+articulo.nombre_articulo
                        articulo.foto_articulo = fs.save(new_path,myfile)
                        fs.delete(old_path)
                    articulo.save()
            context = {'articulo': articulo, 'perfil': perfil, 'lista_reservas': lista_reservas}
            return render(request, 'articulos/vista_articulos_admin.html', context)
        else:
            if request.method == 'POST':
                if 'pedir' in request.POST:
                    form = ReservaForm(request.POST)
                    if form.is_valid():
                        query = ReservaArticulo(perfil=perfil, articulo=articulo, inicio=form.cleaned_data['inicio'], final=form.cleaned_data['fin'])
                        query.save()
                        return HttpResponseRedirect('/exito/')
            else:
                form = ReservaForm()
            context = {'articulo': articulo, 'perfil': perfil, 'lista_reservas': lista_reservas, 'form': form}
            return render(request, 'articulos/vista_articulos_usuarios.html', context)


def editar(request, id_articulo):
    if not request.user.is_authenticated or not request.user.is_superuser:
        return redirect('/home/')
    else:
        perfil = Perfil.objects.get(correo=request.user.id)
        articulo = Articulos.objects.get(pk=id_articulo)
        reservas = ReservaArticulo.objects.filter(articulo=articulo, final__lt=timezone.make_aware(datetime.today(), timezone.get_current_timezone()))
        lista_reservas=list(reservas)
        lista_reservas.sort(key=lambda x: x.final, reverse=True)
        lista_reservas = lista_reservas[:10]
        context = {'articulo': articulo, 'perfil': perfil, 'lista_reservas': lista_reservas}
        return render(request, 'articulos/vista_articulos_admin_edit.html', context)


def exito(request):
    return render(request, 'Layouts/exito.html')

templates/articulos/vista_articulos_admin.html
{% extends "Layouts/GeneralLayout.html" %}
{% load static %}
{% load bootstrap4 %}

{% block cabeza %}

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}"> <!-- CSS reset -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Resource style -->
    <title>{{ articulo.nombre_articulo }}</title>
    <style>
        /*Color del texto en el estado, aparece como no usado, pero se llama al renderizar*/
        .Disponible {
            display: inline-block;
            background:green;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .Prestado {
            display: inline-block;
            background:blue;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .Reparación {
            display: inline-block;
            background:darkorange;
            border-radius: 6px;
        text-align: center;
        color:white;
        float:right;
    }
    .Perdido{
        display: inline-block;
        background:darkred;
        border-radius: 6px;
        text-align: center;
        color:white;
        float:right;
    }
    /*-------------------*/
    .bodycontainer {max-height: 490px; margin: 0; overflow-y: auto; }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- Left Column -->
            <div class="col-8">
                <h1><span class="pull-left">{{ articulo.nombre_articulo }}
                </span> &nbsp <span class="{{ articulo.get_estado_articulo_display }}">
                    &nbsp {{ articulo.get_estado_articulo_display }} &nbsp</span></h1>
                <br/>
                <br/>
                <!-- Foto -->
                <img style="margin-left: 20px; max-height: 300px;max-width: 500px;" class="img-fluid" src={{ articulo.foto_articulo.url }}/>
                <br/>
                <br/>
                <div class="card">
                    <div class="card-body">
                        {{ articulo.descripcion_articulo }}
                    </div>
                </div>
            </div>

            <!-- Right Column -->
            <div class="col-4">
                <div class="col-4 ml-auto">
                    <a class="btn btn-primary" href="edit" role="button">Modificar</a>
                </div>
                <br/>
                <br/>
                <h3>Historial Reservas</h3>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Inicio</th>
                        <th scope="col">Fin</th>
                    </tr>
                    </thead>
                </table>
                <div class="bodycontainer scrollable">
                <table class="table table-hover table-striped table-condensed">
                    <tbody>
                    {% for reserva in lista_reservas %}
                        <tr>
                            <td>{{ reserva.inicio }}</td>
                            <td>{{ reserva.final }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articulos/vista_articulos_admin_edit.html
{% extends "Layouts/GeneralLayout.html" %}
{% load static %}
{% load bootstrap4 %}

{% block cabeza %}

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}"> <!-- CSS reset -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Resource style -->
    <title>{{ articulo.nombre_articulo }}</title>
    <style>
        /*Color del texto en el estado, aparece como no usado, pero se llama al renderizar*/
        .Disponible {
            display: inline-block;
            background:green;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .Prestado {
            display: inline-block;
            background:blue;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
    }
    .Reparación {
        display: inline-block;
        background:darkorange;
        border-radius: 6px;
        text-align: center;
        color:white;
        float:right;
    }
    .Perdido{
        display: inline-block;
        background:darkred;
        border-radius: 6px;
        text-align: center;
        color:white;
        float:right;
    }
    /*-------------------*/
    .bodycontainer {max-height: 490px;width: 100%; margin: 0; overflow-y: auto; }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <form action="/articulos/{{ articulo.id }}/" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
            <!-- Left Column -->
            <div class="col-8">
                <h1>
                    <div class="form-group">
                    <input type="text" value="{{ articulo.nombre_articulo }}" name="new_name" class="form-control form-control-lg">
                    </div>
                </h1>
                <br/>
                <br/>
                <!-- Foto -->
                <img style="margin-left: 20px; max-height: 300px;max-width: 500px;" class="img-fluid" src={{ articulo.foto_articulo.url }}/>
                <br/>
                <br/>
                <div class="form-group">
                    <input type="file" class="form-control-file" name="new_foto">
                    <small class="form-text text-muted">Esta foto remplazará la anterior.</small>
                </div>
                <br/>
                <br/>
                <div class="form-group">
                    <input type="text" value="{{ articulo.descripcion_articulo }}" name="new_descr" class="form-control">
                </div>
            </div>

            <!-- Right Column -->
            <div class="col-4">
                <div class="col-4 ml-auto">
                    <button type="submit" class="btn btn-primary" name="guardar">Guardar</button>
                    <input type="hidden" name="ident" value={{ articulo.id }}>
                </div>
                <br/>
                <br/>
                <h3>Historial Reservas</h3>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Inicio</th>
                        <th scope="col">Fin</th>
                    </tr>
                    </thead>
                </table>
                <div class="bodycontainer scrollable">
                    <table class="table table-hover table-striped table-condensed">
                        <tbody>
                        {% for reserva in lista_reservas %}
                            <tr>
                                <td>{{ reserva.inicio }}</td>
                                <td>{{ reserva.final }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

templates/articulos/vista_articulos_usuarios.html
{% extends "Layouts/GeneralLayout.html" %}
{% load static %}
{% load bootstrap4 %}

{% block cabeza %}

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}"> <!-- CSS reset -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Resource style -->
    <title>{{ articulo.nombre_articulo }}</title>

    <style>
        /*Color del texto en el estado, aparece como no usado, pero se llama al renderizar*/
        .Disponible {
            display: inline-block;
            background:green;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .Prestado {
            display: inline-block;
            background:blue;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .Reparación {
            display: inline-block;
            background:darkorange;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .Perdido{
            display: inline-block;
            background:darkred;
            border-radius: 6px;
            text-align: center;
            color:white;
            float:right;
        }
        .bodycontainer {max-height: 220px;width: 100%; margin: 0; overflow-y: auto; }
        /*-------------------*/
    </style>
{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
        <!-- Left Column -->
        <div class="col-8">
            <h1><span class="pull-left">{{ articulo.nombre_articulo }}</span>
                &nbsp <span class="{{ articulo.get_estado_articulo_display }}">
                    &nbsp {{ articulo.get_estado_articulo_display }} &nbsp</span></h1>
            <br/>
            <br/>
            <!-- Foto -->
            <img style="margin-left: 20px; max-height: 300px;max-width: 500px;" class="img-fluid" src={{ articulo.foto_articulo.url }}/>
            <br/>
            <br/>
            <div class="card">
                <div class="card-body">
                    {{ articulo.descripcion_articulo }}
                </div>
            </div>
        </div>

        <!-- Right Column -->
        <div class="col-4">
            <form action="" method="post" class="form-horizontal">{% csrf_token %}
                <h3>Solicitar Reserva</h3>
                {% bootstrap_form form %}
                <input type="hidden" name="ident" value={{ articulo.id }}>
                {% buttons %}
                    <button type="submit" class="btn btn-primary" name="pedir">Pedir</button>
                {% endbuttons %}
            </form>
            <br/>
            <h3>Historial Reservas</h3>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Inicio</th>
                    <th scope="col">Fin</th>
                </tr>
                </thead>
            </table>
            <div class="bodycontainer scrollable">
                <table class="table table-hover table-striped table-condensed">
                    <tbody>
                    {% for reserva in lista_reservas %}
                        <tr>
                            <td>{{ reserva.inicio }}</td>
                            <td>{{ reserva.final }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}